### PR TITLE
update theme and layout

### PR DESCRIPTION
**Pull request by julianbenegas**

### CODE REVIEW

**Comment by julianbenegas** [comment]
@adamsoffer Vercel is not integrated here?

**Comment by adamsoffer** [comment]
I tried but don't seem to have the permissions. Just asked Eric who's the owner of the github livepeer org.

**Comment by adamsoffer** [comment]
@julianbenegas all set! May have to resubmit the PR to trigger.

**Comment by julianbenegas** [comment]
Awesome!

**Pull request merged**
